ktor:
    application:
        modules:
            - com.iapprusher.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

db.mongo.user: "Bharat"
db.mongo.password: "aadAz0tJHRbFP7mo"
db.mongo.host: "quizphodoindiacluster.hgcjv.mongodb.net"
db.mongo.port: 27017
db.mongo.maxPoolSize: 10
db.mongo.database.name: "phodo_quiz-db"

