ktor:
    application:
        modules:
            - com.iapprusher.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  secret: "7192873h12hkhq9183hjqhadh90183hadkhjdh"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

db:
  mongo:
    user: "Bharat"
    password: "Bharat%402909"
    host: "quizphodoindiacluster.hgcjv.mongodb.net/"
    port: 27017
    maxPoolSize: 10
    database.name: "phodo_quiz-db"
